### ISSUE TITLE
Add timezone support

### ISSUE THREAD

**Issue by mitchhentges** [tickbin/tickbin#136]
If someone uses `tickbin` at home in Kamloops, then jooks to Sweden, it would be sick if they could use times in their current timezone.

Maybe not worth the complexity, but it would be awesome.

**Comment by chrisfosterelli** [comment]
Does anyone know if we currently store dates in UTC or just in the local timezone?

**Comment by jonotron** [comment]
@chrisfosterelli Well, this time entry "12:30-1pm #lunch" stored a `start` as `2016-02-12T20:30:00.000Z`... so, UTC I guess :)

**Comment by jonotron** [comment]
As indicated in #198, the `startArr` and `endArr` (the fields indexed and used for querying) are stored in local timezone, not UTC. This needs to be fixed so that querying across timezone data is reliable.

**Comment by jonotron** [comment]
@mitchhentges What sort of timezone support are you looking for? Once we fix #198 you will be able to enter time in any timezone and it will be stored as UTC. Allowing you to query entries regardless of your current timezone...  E.g. if you record an entry "8am-9am working in Kamloops" it would be recorded as 3pm-4pm UTC and if you were to then "jook", as you say, to Sweeden it would display as 5pm-6pm CET.

Any query you might run would convert your local time query into UTC and then filter entries based on their UTC times... E.g. if you recorded an entry in Kamloops on April 30th 4pm-5pm (which translates to 1am-2am CET) and then from within Sweeden queried for entries from April you would not see the above mentioned entry since it is in May in Sweeden.

**Comment by mitchhentges** [comment]
Yep, I think that that makes sense. #198 should do the trick.

**Comment by jonotron** [comment]
Ok, great! I'm going to close this then in favour of #198
