### ISSUE TITLE
make tick commands more familiar

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#150]
We are currently experiencing some command name mistyping. For example, we often mistake `tick log` for `tick list` as we are used to the `git log` command.

Here is my proposed command changes:

* [x] `tick log` displays entries
* [x] `tick commit` creates new entries 
* [ ] `tick edit` edits existing entries

### Questions?

Should we include aliases (e.g. `tick ls` and `tick list` as an alias to `tick log`) or is that offering too many opinions that could be left to the user to define a custom alias for in their `.bashrc` file?

**Comment by chadfawcett** [comment]
I like these proposed commands. I thought from the beginning it might be nice to have more parity with the git commands.

I don't think we need to implement aliases for `tick log`. There might be cases in the future for example if we were keeping `tick list` it might be useful to have `tick ls` but since we are getting rid of `list` I don't think we should have it.

**Comment by jonotron** [comment]
Did not do `tick edit` since it doesn't exist yet.

**Comment by jonotron** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wZSk8pTq&#x2F;30-tickbin-command-names-ux"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> tickbin: command names UX</a>
