### ISSUE TITLE
index not present on fresh install

### ISSUE THREAD

**Issue by sofia-scho** [tickbin/tickbin#223]
When starting with a fresh database you receive an error. 

```
Sofia:tickbin sofiascholefield$ build/tick.js log
err [Error: Cannot sort on field(s) "startArr" when using the default index]
Sofia:tickbin sofiascholefield$ 
```

**Comment by jonotron** [comment]
I believe the issue here is that indexes are asynchronously created when the user first runs any command.

We could try to wait for index checks before running the logic of the command.

Another approach might be to use some local document which contains the current database version. Check that at every command and re-run whatever installation tasks are needed. This might allow for better support for #221

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
